name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}	
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.20.0
      
      - name: Install Dependencies
        run: npm install
      
      - name: Build
        run: npm run build:prod
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          TOKEN: ${{ secrets.FULL_ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist